version: '3.5'

services:
  nh-user:
    image: cr.yandex/crpd5q7b07g01gbmpiom/nh-user:0.0.2-SNAPSHOT
    environment:
      NH_POSTGRES_JOB_JDBC_URL: "jdbc:postgresql://postgres.cvcljbywqm5j.eu-central-1.rds.amazonaws.com::5432/network_highload"
      NH_POSTGRES_DB_USERNAME: "postgres"
      NH_POSTGRES_DB_PASSWORD: "xxx"
    ports:
      - "8081:8081"

#docker-compose -f dc-nh-yc.yml up -d

#host.docker.internal:5432