version: '3.5'

services:
  nh-user:
    image: public.ecr.aws/v3c4w4q9/nh-user:0.0.2-SNAPSHOT-49baab64
    environment:
      NH_POSTGRES_JOB_JDBC_URL: "jdbc:postgresql://host.docker.internal:5432/network_highload"
    ports:
      - "8081:8081"

#docker-compose -f dc-nh-user.yml up -d

#host.docker.internal:5432