version: '3.5'

services:
  nh-auth:
    image: public.ecr.aws/v3c4w4q9/nh-auth:0.0.3-SNAPSHOT-9e832ac6
    environment:
      NH_READ_POSTGRES_JDBC_URL: "jdbc:postgresql://host.docker.internal:5432/auth"
      NH_WRITE_POSTGRES_JDBC_URL: "jdbc:postgresql://host.docker.internal:5432/auth"
      NH_AUTH_HOST: "host.docker.internal"
    command: server --force-migrate
    ports:
      - "8088:8088"
  nh-user:
    image: public.ecr.aws/v3c4w4q9/nh-user:0.0.3-SNAPSHOT-9e832ac6
    environment:
      NH_READ_POSTGRES_JDBC_URL: "jdbc:postgresql://host.docker.internal:5432/nh_user"
      NH_WRITE_POSTGRES_JDBC_URL: "jdbc:postgresql://host.docker.internal:5432/nh_user"
      NH_AUTH_HOST: "host.docker.internal"
    command: server --force-migrate
    ports:
      - "8081:8081"
  nh-conversation:
    image: public.ecr.aws/v3c4w4q9/nh-conversation:0.0.3-SNAPSHOT-9e832ac6
    environment:
      NH_READ_POSTGRES_JDBC_URL: "jdbc:postgresql://host.docker.internal:5432/conversation"
      NH_WRITE_POSTGRES_JDBC_URL: "jdbc:postgresql://host.docker.internal:5432/conversation"
      NH_AUTH_HOST: "host.docker.internal"
    command: server --force-migrate
    ports:
      - "8082:8082"
  nh-post:
    image: public.ecr.aws/v3c4w4q9/nh-post:0.0.3-SNAPSHOT-9e832ac6
    environment:
      NH_READ_POSTGRES_JDBC_URL: "jdbc:postgresql://host.docker.internal:5432/post"
      NH_WRITE_POSTGRES_JDBC_URL: "jdbc:postgresql://host.docker.internal:5432/post"
      NH_AUTH_HOST: "host.docker.internal"
      NH_USER_HOST: "host.docker.internal"
    command: server --force-migrate
    ports:
      - "8083:8083"

#docker-compose -f dc-nh-local.yml up -d

#host.docker.internal:5432