version: '3.7'
services:
  nginx:
    image: nginx:1.21
    container_name: nginx-lb
    restart: on-failure
    networks:
      - otus-nginx-demo
    volumes:
      - "./default.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "4088:80"
      - "4098:8080"

  backend-1:
    image: nginxdemos/nginx-hello
    container_name: nginx-backend-1
    restart: "no"
    networks:
      - otus-nginx-demo

  backend-2:
    image: nginxdemos/nginx-hello
    container_name: nginx-backend-2
    restart: "no"
    networks:
      - otus-nginx-demo

  backend-3:
    image: nginxdemos/nginx-hello
    container_name: nginx-backend-3
    restart: "no"
    networks:
      - otus-nginx-demo

networks:
  otus-nginx-demo:
    external: true
